elfin_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - elfin_joint1
     - elfin_joint2
     - elfin_joint3
     - elfin_joint4
     - elfin_joint5
     - elfin_joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1

  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10
mecanum_controller:
  type: mecanum_controller/MecanumController
  front_wheel:
    - forward_left_wheel_joint
    - forward_right_wheel_joint
  rear_wheel:
    - back_left_wheel_joint
    - back_right_wheel_joint
  track: 0.5
  wheel_radius: 0.15
  wheel_base: 0.5
  pose_covariance_diagonal: [1.0, 0.1, 0.1, 0.01, 0.01, 0.001]
  twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.01, 0.01, 0.01]



