elfin_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - elfin_joint1
    - elfin_joint2
    - elfin_joint3
    - elfin_joint4
    - elfin_joint6
    - elfin_joint5
  gains:
    elfin_joint1: { p: 10000.0, i: 0, d: 75.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: false }
    elfin_joint2: { p: 50000.0, i: 0, d: 450.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: false }
    elfin_joint3: { p: 7500.0, i: 0, d: 50.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: false }
    elfin_joint4: { p: 800.0, i: 0.0, d: 150.0, i_clamp_max: 0, i_clamp_min: 0.0, antiwindup: true, publish_state: false }
    elfin_joint5: { p: 1500.0, i: 0, d: 50.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: false }
    elfin_joint6: { p: 500.0, i: 0, d: 75.0, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: false }
constraints:
  elfin_joint1: { trajectory: 0.02, goal: 0.01 }
  elfin_joint2: { trajectory: 0.01, goal: 0.01 }
  elfin_joint3: { trajectory: 0.01, goal: 0.01 }
  elfin_joint4: { trajectory: 0.03, goal: 0.015 }
  eflin_joint5: { trajectory: 0.03, goal: 0.01 }
  elfin_joint6: { trajectory: 0.01, goal: 0.01 }
elfin_arm_one_joint_controller:
  type: effort_controllers/JointGroupEffortController
  joints: 
    - elfin_joint1
    - elfin_joint2
    - elfin_joint3
    - elfin_joint4
    - elfin_joint5
    - elfin_joint6
mecanum_controller:
  type: mecanum_controller/MecanumController
  front_wheel:
    - forward_left_wheel_joint
    - forward_right_wheel_joint
  rear_wheel:
    - back_left_wheel_joint
    - back_right_wheel_joint
  track: 0.5
  wheel_radius: 0.15
  wheel_base: 0.5
  pose_covariance_diagonal: [1.0, 0.1, 0.1, 0.01, 0.01, 0.001]
  twist_covariance_diagonal: [0.1, 0.1, 0.1, 0.01, 0.01, 0.01]




